version: '3.5'
services:
  api1: # API - Instância 01
    image: api
    hostname: api1
    build:
      context: .
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      POSTGRES_ADDRESS: db
      POSTGRES_PASSWORD: 'rinha'
      POSTGRES_USER: 'rinha'
      POSTGRES_DB: 'rinha'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2: # API - Instância 01
    image: api
    hostname: api2
    build:
      context: .
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      POSTGRES_ADDRESS: db
      POSTGRES_PASSWORD: 'rinha'
      POSTGRES_USER: 'rinha'
      POSTGRES_DB: 'rinha'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx: # Load Balancer
   image: nginx:latest
   volumes:
     - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
   depends_on:
     - api1
     - api2
   ports:
     - "9999:9999"
   deploy:
     resources:
       limits:
         cpus: '0.25'
         memory: '0.5GB'

  db: # Banco de dados
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'rinha'
      POSTGRES_USER: 'rinha'
      POSTGRES_DB: 'rinha'
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '1.4GB'